name: 'dual-run-action-example'
description: 'An example of a program that can be run either directly or via GitHub Actions.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Alex'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index-action.js'